version: '3.9'
services:
    nginx:
        image: nginx:latest
        ports:
            - "8080:80"
        volumes:
            - ./app:/var/www/app
            - ./docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
        working_dir: /var/www/app
        depends_on:
            - php-fpm

    php-cli:
        build:
            context: .
            dockerfile: ./docker/php/php-cli.docker
        environment:
            APP_ENV: dev
        volumes:
            - ./app:/var/www/app
        working_dir: /var/www/app
        depends_on:
            - postgres

    php-fpm:
        build:
            context: .
            dockerfile: ./docker/php/php-fpm.docker
        environment:
            APP_ENV: dev
        volumes:
            - ./app:/var/www/app
        working_dir: /var/www/app
        depends_on:
            - postgres

    postgres:
        image: postgres:alpine
#        restart: always
        volumes:
            - pgdata:/var/lib/postgresql/data
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: sfbasic
        ports:
            - "5432:5432"

    manager-node:
        image: node:current-alpine
        volumes:
            - ./app:/var/www/app
        working_dir: /var/www/app

volumes:
    pgdata:
        driver: local